databases:
  - name: fastblog
    plan: free
    databaseName: fastblog
    user: fastblog

services:
  - type: web
    plan: free
    name: fastblog
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn config.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fastblog
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4